### ISSUE TITLE
Azure indexer tests that don't pass

### ISSUE THREAD

**Issue by mikedennis** [stratisproject/BlockExplorer#40]
* CanGetColoredTransaction
* CanImportMainChain

Both fail with:
``` 
Message: NBitcoin.Protocol.ProtocolException : An header which does not pass proof of work verification has been received
```

**Comment by quantumagi** [comment]
Following recent PR's these errors are no longer being observed, so perhaps the issue can be closed?

**Comment by mikedennis** [comment]
I will give them a quick test again and close this if they pass. Thanks!

**Comment by mikedennis** [comment]
Yes tests all pass now - Thanks!
